### ISSUE TITLE
How to install external libraries

### ISSUE THREAD

**Issue by 8tm** [codrsquad/portable-python#17]
Hi,
how can I install external libraries so that the packed tar.gz file already has a set of libraries?
At the moment there is an option to unpack the files, install the libraries and repack the files into tar.gz files, but could it be simplified?

**Comment by zsimic** [comment]
Do you mean additional python libraries? As in `.../bin/pip install ...`?
If so, that could be a nice additional feature, not possible right now, but could be added via a configuration entry

**Comment by 8tm** [comment]
Yes because I would like to add additional libraries like Pillow, PyQt5, PyYaml etc

**Comment by 8tm** [comment]
My current solution is additional script which will build for me tar.gz file in docker and then update it:

`
#!/bin/sh

set -e
PYTHON3_VERSION="3.9.11"
TMP_PATH="/tmp/portable-python"

portable-python -c portable-python.yml build ${PYTHON3_VERSION} -m libffi,zlib,xz,bzip2,readline,openssl,sqlite,bdb,gdbm,uuid

if [ ! -x /src/dist/cpython-${PYTHON3_VERSION}-linux-x86_64.tar.gz ]; then
    set -x
    mkdir -p "${TMP_PATH}"
    tar -C ${TMP_PATH}/ -xf /src/dist/cpython-${PYTHON3_VERSION}-linux-x86_64.tar.gz
    ${TMP_PATH}/${PYTHON3_VERSION}/bin/pip install Pillow==10.0.0 ansible-core==2.12.3
    tar -czvf /src/dist/cpython-${PYTHON3_VERSION}-linux-x86_64_UPDATED.tar.gz -C ${TMP_PATH}/ ${PYTHON3_VERSION}
fi
`

**Comment by 8tm** [comment]
Added additional option "cpython-additional-packages" to portable-python.yml file (list of packages).
